var express = require('express');
var bodyParser = require('body-parser');
var app = express();
var port = process.env.PORT || 8081;

// Configure express body-parser as middleware
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());

app.get('/', function(req, res) {

    let models = [
        'cat',
        'bird',
        'bicycle',
        'octopus',
        'face',
        'flamingo',
        'cruise_ship',
        'truck',
        'pineapple',
        'spider',
        'mosquito',
        'angel',
        'butterfly',
        'pig',
        'garden',
        'the_mona_lisa',
        'crab',
        'windmill',
        'yoga',
        'hedgehog',
        'castle',
        'catbus',
        'ant',
        'basket',
        'chair',
        'bridge',
        'diving_board',
        'firetruck',
        'flower',
        'owl',
        'palm_tree',
        'pig',
        'rain',
        'skull',
        'duck',
        'snowflake',
        'speedboat',
        'sheep',
        'scorpion',
        'sea_turtle',
        'pool',
        'paintbrush',
        'catpig',
        'bee',
        'antyoga',
        'beeflower',
        'backpack',
        'ambulance',
        'barn',
        'bus',
        'cactus',
        'calendar',
        'couch',
        'elephantpig',
        'floweryoga',
        'hand',
        'helicopter',
        'lighthouse',
        'lion',
        'parrot',
        'passport',
        'peas',
        'postcard',
        'power_outlet',
        'radio',
        'snail',
        'stove',
        'strawberry',
        'swan',
        'swing_set',
        'tiger',
        'toothpaste',
        'toothbrush',
        'trombone',
        'yogabicycle',
        'whale',
        'tractor',
        'radioface',
        'squirrel',
        'pigsheep',
        'lionsheep',
        'alarm_clock',
        'bear',
        'book',
        'brain',
        'bulldozer',
        'crabchair',
        'crabrabbitfacepig',
        'dog',
        'dogbunny',
        'dolphin',
        'elephant',
        'eye',
        'fan',
        'fire_hydrant',
        'frog',
        'frogsofa',
        'hedgeberry',
        'kangaroo',
        'key',
        'lantern',
        'lobster',
        'map',
        'mermaid',
        'monapassport',
        'monkey',
        'penguin',
        'rabbit',
        'rabbitturtle',
        'rhinoceros',
        'rifle',
        'roller_coaster',
        'sandwich',
        'steak'
    ];
    let type = 'gen';
    res.json(models.map(x => 'https://storage.googleapis.com/quickdraw-models/sketchRNN/large_models/' + x + '.' + type + '.json'));

});

/**
 * Start the http server.
 */
app.listen(port);
console.log('Server started at http://localhost:' + port);